### ISSUE TITLE
Parsing fails on parens inside filter criterion

### ISSUE THREAD

**Issue by Srisaibersys** [gatling/jsonpath#27]
We already have discussed this issue https://github.com/gatling/jsonpath/issues/23
It's still reproduce with following versions
```
dependencies {
//  compile ('commons-collections:commons-collections:3.2')
    compile ('org.scala-lang:scala-library:2.11.8')
    compile ('org.scala-lang:scala-compiler:2.11.8')
    compile ('io.gatling:gatling-core:2.2.3')
    compile ('io.gatling:gatling-app:2.2.3')
    compile ('io.gatling.highcharts:gatling-charts-highcharts:2.2.3') 
}
```
Here are the scenarios
1. `$.error[?(@.foo=='bar[baz]')]`

jsonPath($.error[?(@.errorMessage==' [ SERVICES-1021 : No devices exist for this account. ] ')]).find(0).exists, found nothing

2. `$.error[?(@.foo=='bar(baz)')]`

3. `.check(regex(errorMessages.get("errorMessage2")).exists)`

KO regex(Exception from AMS service while calling getBillingArrangementDC1,actualError=Not Found [404]).find.exists, found nothing

Please let us know if you need more information regarding this?

**Comment by Srisaibersys** [comment]
We also tried to escape the special character using 
1. \[404]\
2. \\[404]\\
3. \\\[404]\\\
4. \\\\[404]\\\\
Here is the exception for 2nd example

```
java.util.regex.PatternSyntaxException: Unexpected internal error near index 95
Exception from AMS service while calling getBillingArrangementDC1,actualError=Not Found \[404]\
                                                                                               ^
	at java.util.regex.Pattern.error(Pattern.java:1955)
	at java.util.regex.Pattern.compile(Pattern.java:1702)
	at java.util.regex.Pattern.<init>(Pattern.java:1351)
	at java.util.regex.Pattern.compile(Pattern.java:1028)
	at io.gatling.core.check.extractor.regex.Patterns.io$gatling$core$check$extractor$regex$Patterns$$$anonfun$1(Patterns.scala:28)
	at io.gatling.core.util.cache.Cache$$anon$1.load(Cache.scala:40)
	at com.github.benmanes.caffeine.cache.BoundedLocalCache$BoundedLocalLoadingCache.lambda$new$0(BoundedLocalCache.java:3159)
	at com.github.benmanes.caffeine.cache.BoundedLocalCache.lambda$doComputeIfAbsent$16(BoundedLocalCache.java:1984)
	at java.util.concurrent.ConcurrentHashMap.compute(ConcurrentHashMap.java:1853)
	at com.github.benmanes.caffeine.cache.BoundedLocalCache.doComputeIfAbsent(BoundedLocalCache.java:1982)
	at com.github.benmanes.caffeine.cache.BoundedLocalCache.computeIfAbsent(BoundedLocalCache.java:1965)
	at com.github.benmanes.caffeine.cache.LocalCache.computeIfAbsent(LocalCache.java:113)
	at com.github.benmanes.caffeine.cache.LocalLoadingCache.get(LocalLoadingCache.java:67)
	at io.gatling.core.check.extractor.regex.Patterns.compilePattern(Patterns.scala:38)
	at io.gatling.core.check.extractor.regex.RegexExtractorFactory$$anon$2.extract(RegexExtractorFactory.scala:26)
	at io.gatling.core.check.extractor.regex.RegexExtractorFactory$$anon$2.extract(RegexExtractorFactory.scala:23)
	at io.gatling.core.check.extractor.CriterionExtractorFactory$$anon$1.extract(CriterionExtractorFactory.scala:43)
	at io.gatling.core.check.extractor.CriterionExtractor.apply(Extractor.scala:33)
	at io.gatling.core.check.CheckBase.io$gatling$core$check$CheckBase$$$anonfun$7(Check.scala:86)
	at io.gatling.commons.validation.Success.flatMap(Validation.scala:33)
	at io.gatling.core.check.CheckBase.io$gatling$core$check$CheckBase$$$anonfun$5(Check.scala:85)
	at io.gatling.commons.validation.Success.flatMap(Validation.scala:33)
	at io.gatling.core.check.CheckBase.io$gatling$core$check$CheckBase$$$anonfun$3(Check.scala:84)
	at io.gatling.commons.validation.Success.flatMap(Validation.scala:33)
	at io.gatling.core.check.CheckBase.check(Check.scala:83)
	at io.gatling.http.check.HttpCheck.check(HttpCheck.scala:35)
	at io.gatling.http.check.HttpCheck.check(HttpCheck.scala:32)
	at io.gatling.core.check.Check$.checkRec$1(Check.scala:37)
	at io.gatling.core.check.Check$.check(Check.scala:60)
	at io.gatling.http.ahc.ResponseProcessor.checkAndProceed$1(ResponseProcessor.scala:282)
	at io.gatling.http.ahc.ResponseProcessor.processResponse(ResponseProcessor.scala:323)
	at io.gatling.http.ahc.ResponseProcessor.onCompleted(ResponseProcessor.scala:61)
	at io.gatling.http.ahc.AsyncHandler.io$gatling$http$ahc$AsyncHandler$$$anonfun$1(AsyncHandler.scala:136)
	at io.gatling.http.ahc.AsyncHandler.io$gatling$http$ahc$AsyncHandler$$$anonfun$1$adapted(AsyncHandler.scala:134)
	at io.gatling.http.ahc.AsyncHandler.withResponse(AsyncHandler.scala:127)
	at io.gatling.http.ahc.AsyncHandler.onCompleted(AsyncHandler.scala:134)
	at io.gatling.http.ahc.AsyncHandler.onCompleted(AsyncHandler.scala:47)
	at org.asynchttpclient.netty.NettyResponseFuture.getContent(NettyResponseFuture.java:181)
	at org.asynchttpclient.netty.NettyResponseFuture.done(NettyResponseFuture.java:215)
	at org.asynchttpclient.netty.handler.HttpHandler.finishUpdate(HttpHandler.java:58)
	at org.asynchttpclient.netty.handler.HttpHandler.handleChunk(HttpHandler.java:159)
	at org.asynchttpclient.netty.handler.HttpHandler.handleRead(HttpHandler.java:187)
	at org.asynchttpclient.netty.handler.AsyncHttpClientHandler.channelRead(AsyncHttpClientHandler.java:76)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:367)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:353)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:346)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:367)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:353)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:346)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:367)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:353)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:346)
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:435)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:293)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:267)
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:250)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:367)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:353)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:346)
	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1069)
	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:902)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:411)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:248)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:367)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:353)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:346)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1294)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:367)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:353)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:911)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:652)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:575)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:489)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:451)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:140)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by slandelle** [comment]
@Srisaibersys Please provide a JSON payload and your exact JSONPath expression to reproduce.

**Comment by slandelle** [comment]
@Srisaibersys I've add a unit test with your sample proving that Gatling and our JsonPath implementation behaves as expected with regard to JsonPath expressions with filters containing square braces.

Either the problem is elsewhere in Gatling, or that the issue is actually on your side, in the way you use Gatling, or in your system under test.

Nothing we can do without you providing a way to reproduce for sure your problem.
